plugin: amazon.aws.aws_ec2
regions:
  - us-east-1
filters:
  tag:Name: ivolve
keyed_groups:
  - key: tags.Name
    prefix: tag
hostnames:
  - public-ip-address
compose:
  ansible_host: public_dns_name
  ansible_user: ec2-user
s if needed
 other AMIs
