pipeline {
    agent any

    environment {
        DOCKER_USERNAME = credentials('Docker-User')
        DOCKER_PASSWORD = credentials('Docker-Password')
        DOCKER_IMAGE = "${DOCKER_USERNAME}/jenkins-app-lab37:${BUILD_NUMBER}"
        K8S_TOKEN = credentials('token')
        NAMESPACE = 'ivolve'
        DEPLOYMENT_FILE = 'Jenkins/Lab37_argocd/CD_repo/deployment.yaml'
        GIT_CREDENTIALS_ID = 'github'
    }

    stages {
        stage('Build Application') {
            steps {
              dir('Jenkins/Lab37_argocd/CI_repo'){  
                echo 'Building application...'
                sh 'mvn clean package'}
            }
        }

        stage('Build Docker Image') {
            steps {
              dir('Jenkins/Lab37_argocd/CI_repo'){
                echo 'Building Docker image...'
                sh 'docker build -t $DOCKER_IMAGE .'
            }
          }      
        }

        stage('Push Docker Image to Docker Hub') {
            steps {
              dir('Jenkins/Lab37_argocd/CI_repo'){
                echo 'Pushing Docker image to Docker Hub...'
                sh '''
                    echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
                    docker push $DOCKER_IMAGE
                '''
               }
            }      
        }

        stage('Clone ArgoCD Manifests Repo') {
            steps {
                 dir('Jenkins/Lab37_argocd/CD_repo') {
                    git branch: 'master',
                        credentialsId: GIT_CREDENTIALS_ID,
                        url: 'https://github.com/Orabi20/iVOLVE-OJT'
                 }
            }
        }

        stage('Update Deployment File with New Image') {
            steps {
                dir('Jenkins/Lab37_argocd/CD_repo') {
                    withCredentials([usernamePassword(credentialsId: GIT_CREDENTIALS_ID, usernameVariable: 'GIT_USERNAME', passwordVariable: 'GIT_PASSWORD')]) {
                        sh '''
                            git config user.name "jenkins"
                            git config user.email "jenkins@example.com"

                            sed -i 's|image:.*|image: '"$DOCKER_IMAGE"'|' $DEPLOYMENT_FILE
                            git add $DEPLOYMENT_FILE
                            git commit -m "Update image to $DOCKER_IMAGE" || echo "No changes to commit"
                            git push https://$GIT_USERNAME:$GIT_PASSWORD@github.com/Orabi20/iVOLVE-OJT.git
                        '''
                    }
                }
            }
        }
    }

    post {
        always {
            echo 'Cleaning up workspace...'
            sh 'rm -rf argocd-yaml || true'
        }
        success {
            echo 'Pipeline completed successfully.'
        }
        failure {
            echo 'Pipeline failed.'
        }
    }
}

