---
- name: Install and configure MySQn
  hosts: db_servers
  become: yes
  vars_files:
       vars/all_vars.yml

  tasks:
    - name: Install MySQL server
      yum:
        name: mysql-server
        state: present

    - name: Start and enable MySQL
      service:
        name: mysqld
        state: started
        enabled: true

    - name: Wait for MySQL to be ready
      wait_for:
        path: /var/lib/mysql/mysql.sock
        state: present
        timeout: 30

    - name: Create iVolve database
      shell: |
        mysql -u root -e "CREATE DATABASE IF NOT EXISTS iVolve;"
      args:
        warn: false

    - name: Create MySQL user
      shell: |
        mysql -u root -e "CREATE USER IF NOT EXISTS '{{ db_user }}'@'%' IDENTIFIED BY '{{ db_password }}';"
      args:
        warn: false

    - name: Grant all privileges on iVolve to user
      shell: |
        mysql -u root -e "GRANT ALL PRIVILEGES ON iVolve.* TO '{{ db_user }}'@'%'; FLUSH PRIVILEGES;"
      args:
        warn: false

    - name: Validate List databases as created user
      shell: |
        mysql -u {{ db_user }} -p{{ db_password }} -e "SHOW DATABASES;" | grep iVolve
      register: validation_output
      

    - name: Show validation output
      debug:
        var: validation_output.stdout_lines
