---
- name: Configure Nginx Web Server
  hosts: tag_ivolve
  become: true
  tasks:

    - name: Install Nginx
      ansible.builtin.yum:
        name: nginx
        state: present

    - name: Ensure Nginx is started and enabled
      ansible.builtin.service:
        name: nginx
        state: started
        enabled: yes

    - name: Customize the Nginx homepage
      ansible.builtin.copy:
        dest: /usr/share/nginx/html/index.html
        content: |
          <!DOCTYPE html>
          <html lang="en">
          <head>
              <meta charset="UTF-8" />
              <meta name="viewport" content="width=device-width, initial-scale=1.0" />
              <title>Lab8 by Ahmed Orabi</title>
              <style>
                  @import url('https://fonts.googleapis.com/css2?family=Red+Hat+Display:wght@500;700&display=swap');
                  body {
                      margin: 0;
                      font-family: 'Red Hat Display', sans-serif;
                      background: linear-gradient(135deg, #e6e6e6, #ffffff);
                      color: #1a1a1a;
                      display: flex;
                      justify-content: center;
                      align-items: center;
                      height: 100vh;
                  }
                  .container {
                      text-align: center;
                      padding: 40px;
                      border: 4px solid #cc0000;
                      border-radius: 20px;
                      background: #fff5f5;
                      box-shadow: 0 0 20px rgba(204, 0, 0, 0.3);
                  }
                  h1 {
                      font-size: 4rem;
                      color: #cc0000;
                      margin-bottom: 10px;
                  }
                  p {
                      font-size: 1.8rem;
                      color: #333;
                  }
              </style>
          </head>
          <body>
              <div class="container">
                  <h1>Lab8</h1>
                  <p>by Ahmed Orabi</p>
              </div>
          </body>
          </html>
        owner: root
        group: root
        mode: '0644'
        
      